<?xml version="1.0" encoding="utf-8" ?>

<!--
    (C) Copyright David Goodwin, 2025.
    Permission is granted to copy, distribute and/or modify this document under
    the terms of the GNU Free Documentation License, Version 1.3 or any later
    version published by the Free Software Foundation; with no Invariant
    Sections, no Front-Cover Texts, and no Back-Cover Texts.
-->

<!--
This DTD is just here to help editors catch mistakes; the tool for converting
this document to HTML isn't quite as strict, and the DTD is not comprehensive.
-->
<!DOCTYPE document [
        <!ENTITY mdash "-">
        <!-- TODO - that really should be a proper mdash, but something
             (Regina REXX?) is converting everything to ASCII causing it to be
              mangled-->

        <!ATTLIST document title CDATA #REQUIRED>

        <!ELEMENT index EMPTY>

        <!ELEMENT badge-def EMPTY>
        <!ATTLIST badge-def name ID #REQUIRED>
        <!ATTLIST badge-def colour CDATA #IMPLIED>
        <!ATTLIST badge-def comment CDATA #IMPLIED>
        <!ATTLIST badge-def fg-color CDATA #IMPLIED>
        <!ATTLIST badge-def sort-order CDATA #IMPLIED>
        <!ELEMENT badges (badge-def)*>

        <!ELEMENT badge EMPTY>
        <!ATTLIST badge name IDREF #IMPLIED>
        <!ATTLIST badge group IDREF #IMPLIED>

        <!ELEMENT badgegroup-ref EMPTY>
        <!ATTLIST badgegroup-ref name IDREF #REQUIRED>

        <!ELEMENT badgegroup (badge|badgegroup-ref)*>
        <!ATTLIST badgegroup name ID #REQUIRED>
        <!ELEMENT badgegroups (badgegroup)*>


        <!ELEMENT k95info EMPTY>
        <!ATTLIST k95info val (herald|version-number|release|release-actual|version-full|version-date|version-date-short|version-date-iso|version-major|version-minor|version-rev|processed-date|processed-time) #REQUIRED>

        <!ELEMENT br EMPTY>

        <!ELEMENT em (#PCDATA)>
        <!ELEMENT cc (#PCDATA)>
        <!ELEMENT tt (#PCDATA|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ELEMENT pre (#PCDATA|b|cc)*>
        <!ELEMENT b (#PCDATA)>
        <!ELEMENT u (#PCDATA)>

        <!ELEMENT li (#PCDATA|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>

        <!ELEMENT ul (li)*>

        <!ELEMENT ol (li)*>

        <!ELEMENT dt (#PCDATA)>
        <!ATTLIST dt not-implemented (true|false) #IMPLIED>
        <!ELEMENT dd (#PCDATA|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>


        <!ELEMENT dl (dt,dd)*>

        <!ELEMENT a (#PCDATA|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ATTLIST a href CDATA #REQUIRED>

        <!ELEMENT param-single EMPTY>
        <!ATTLIST param-single symbol CDATA #IMPLIED>
        <!ATTLIST param-single value CDATA #IMPLIED>
        <!ATTLIST param-single description CDATA #IMPLIED>

        <!ELEMENT param-char EMPTY>
        <!ATTLIST param-char symbol CDATA #IMPLIED>
        <!ATTLIST param-char value CDATA #IMPLIED>
        <!ATTLIST param-char description CDATA #IMPLIED>

        <!ELEMENT param-multi EMPTY>
        <!ATTLIST param-multi symbol CDATA #IMPLIED>
        <!ATTLIST param-multi value CDATA #IMPLIED>
        <!ATTLIST param-multi description CDATA #IMPLIED>

        <!ELEMENT param-text EMPTY>
        <!ATTLIST param-text symbol CDATA #IMPLIED>
        <!ATTLIST param-text value CDATA #IMPLIED>
        <!ATTLIST param-text description CDATA #IMPLIED>

        <!ELEMENT p (#PCDATA|br|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ATTLIST p role (code-reference|note|warning) #IMPLIED>
        <!ATTLIST p badges IDREFS #IMPLIED>
        <!ATTLIST p groups IDREFS #IMPLIED>
        <!ATTLIST p exclude-badges IDREFS #IMPLIED>

        <!ELEMENT th (#PCDATA|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>

        <!ELEMENT td (#PCDATA|a|em|cc|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info|br|table)*>
        <!ATTLIST td not-implemented (true|false) "false">
        <!ATTLIST td style CDATA #IMPLIED>
        <!ATTLIST td colspan CDATA #IMPLIED>

        <!ELEMENT tr (th|td)*>
        <!ATTLIST tr not-implemented (true|false) "false">

        <!ELEMENT table (tr)*>

        <!ELEMENT ctlseq (#PCDATA|param-char|param-single|param-multi|param-text)*>

        <!ELEMENT ref EMPTY>
        <!ATTLIST ref src CDATA #REQUIRED>
        <!ATTLIST ref comment CDATA #IMPLIED>

        <!ELEMENT termsupp EMPTY>
        <!ATTLIST termsupp series (vt|wyse|xt|k95|sco|rxvt|ansi|tt|linux|putty|wt|print|wz|dtc) #REQUIRED>
        <!ATTLIST termsupp first (vt50|vt50h|vt52|vt100|vt102|vt105|vt132|vt220|vt22z|vt320|vt330|vt340|vt420|vt510|vt520|vt525|msk|k95|xterm|tt|wy370|ansi|sco|vt382|linux|putty|decterm|vt1000|vws|uws|dtterm|wt|la100|wz|lqp02|lcg01|lj250|ln05|vk100|dtc01|la75|ln01|ln08|ln03|la30|lg31|lgp01|lg06) #REQUIRED>
        <!ATTLIST termsupp additional CDATA #IMPLIED>
        <!ATTLIST termsupp excluded CDATA #IMPLIED>

        <!ELEMENT implchk EMPTY>
        <!ATTLIST implchk std070 (true|false) "false">
        <!ATTLIST implchk xt CDATA "">

        <!ELEMENT section (ctlseq|ref|termsupp|implchk|p|ul|ol|dl|section|pre|table)*>
        <!ATTLIST section id ID #IMPLIED>
        <!ATTLIST section title CDATA #IMPLIED>
        <!ATTLIST section ctlseq CDATA #IMPLIED>
        <!ATTLIST section toc (true|false) "false">
        <!ATTLIST section groups IDREFS #IMPLIED>
        <!ATTLIST section badges IDREFS #IMPLIED>
        <!ATTLIST section exclude-badges IDREFS #IMPLIED>
        <!ATTLIST section exclude-groups IDREFS #IMPLIED>
        <!ATTLIST section hide-badges IDREFS #IMPLIED>
        <!ATTLIST section hide-groups IDREFS #IMPLIED>
        <!ATTLIST section style (box|group|none) "none">
        <!ATTLIST section not-implemented (true|false) "false">
        <!ATTLIST section todo (true|false) "false">
        <!ATTLIST section role (text|ctlseq|ctlchar|parameter|group) #REQUIRED>
        <!ATTLIST section formats CDATA #IMPLIED>
        <!ATTLIST section mnemonic CDATA #IMPLIED>

        <!ELEMENT refsrc EMPTY>
        <!ATTLIST refsrc key CDATA #REQUIRED>
        <!ATTLIST refsrc uri CDATA #IMPLIED>
        <!ATTLIST refsrc name CDATA #REQUIRED>
        <!ATTLIST refsrc uri-type (anchor|prefix|direct|pdf-page) #REQUIRED>
        <!ATTLIST refsrc sort-order CDATA #REQUIRED>
        <!ATTLIST refsrc pdf-page-offset CDATA #IMPLIED>
        <!ATTLIST refsrc badge IDREF #IMPLIED>

        <!ELEMENT references (refsrc)*>

        <!ELEMENT style (#PCDATA)>
        <!ELEMENT script (#PCDATA)>
        <!ELEMENT html (style?|script?)>
        <!ATTLIST html filename CDATA #REQUIRED>
        <!ATTLIST html type (document|outline|ctlseq-table|term-ctlseqs|all-ctlseqs|todo) #REQUIRED>
        <!ATTLIST html title CDATA #IMPLIED>
        <!ATTLIST html terminals CDATA #IMPLIED>
        <!ATTLIST html todo-ids CDATA #IMPLIED>  <!-- for "todo" type only -->
        <!ATTLIST html todo-mnemonics CDATA #IMPLIED>  <!-- for "todo" type only -->
        <!ATTLIST html include CDATA #IMPLIED> <!-- for "term-ctlseqs" type only -->
        <!ATTLIST html show-refs (true|false) "false"> <!-- for table outputs only -->
        <!ATTLIST html as-table (true|false) "false"> <!-- as table output -->
        <!ATTLIST html show-not-implemented (true|false) "false">
        <!ATTLIST html show-termsupp (true|false) "false"> <!-- for table outputs only -->

        <!ELEMENT outputs (html)*>

        <!ELEMENT document (references | badges | badgegroups | outputs | section | index)*>
]>
<document title="Kermit 95 Control Sequences">

    <!--
    ////////////////////////////// README //////////////////////////////
    This is the source document used to generate ctlseqs.html and a few other
    related files. This XML file is *not* some variant of XHTML, even if some
    tags kind of look like XHTML. It is a custom XML document format
    and converter tool built specifically for this document.

    Why use a custom XML format for ctlseqs.html? For easier long-term
    maintenance. In particular:
      - To allow bulk changes to terminal type restrictions more possible
      - To make programmatic transformation of this documents structure
        more possible should it be needed some day
      - To make changes to the output *style* easier than with CSS
        alone
      - To allow conversion to other non-HTML formats in the future if
        there is a need.
      - To support generation of multiple different documents from a single
        source

    The document is organized thusly:
      - Reference sources: locations for various terminal and terminal
        emulator documentation
      - Badges and badge groups: identifiers for K95s various terminal
        emulation profiles
      - Outputs: definitions and stylesheets for the various documents
        that will be generated
      - Sections that make up the document itself

    About Sections:
      Sections are the basic blocks that make up the document. All content
      included in the output (aside from CSS) lives within a section.

      Sections can optionally have a title. Where one is specified, it will
      be included in the generated document as a heading or, if the section
      is nested within another section, a subheading. Sections can also be
      used without a heading simply to group content together within the
      document for applying common attributes. Attributes such as:

        - Which terminal types the sections content is relevant to (badges)
        - Whether the content described by the section has actually been
          implemented in Kermit 95
        - Which output documents the sections *content* should be included
          in.

      In addition to the above attributes a section has a role which
      describes what sort of content the section has. This can be one of:

        - text: general text, no special treatment
        - group: No semantic meaning, the section is just grouping other
          sections together. Depending on the roles of the other sections
          it contains, it may affect how they're rendered (such as less
          padding between section headings)
        - ctlseq or ctlchar: the section describes a specific control
          sequence or control character
        - parameter: Only valid inside a section with the ctlseq role,
          a parameter section describes a parameter for the parent control
          sequence or control character

      Sections with the ctlseq, ctlchar or parameter roles must have a
      control sequence specified, either via the ctlseq attribute, or by
      one or more child ctlseq elements. This specifies the control
      sequence or parameter/parameter-value the section is describing.

      A ctlseq, ctlchar or parameter section *should* also have one ref
      element for each terminal that supports it. The ref elements provide
      links to documentation where a terminals support for the control
      sequence/parameter is described, providing proof that that terminal
      does support it. In cases where references aren't available, the
      termsupp element can be explicitly used to state which real terminals
      support it.

      The implchk element states which, if any, reference implementations K95s
      implementation of a control sequence has been checked against:
        std070: the pseudo-code in DEC STD 070. True/false.
        xt: Xterm. Value is xterm version checked against.

      Ctlseq, ctlchar and parameter sections can still have textual content
      just like a regular section with the text role. This textual content
      should describe the control sequence/character or its parameters, what
      restrictions and behaviors apply, etc. But for some outputs generated
      from this file that textual content may be excluded.

    What are these badges and groups anyway?
      A badge is used to indicate terminal-type-specific behavior.
      Maybe a particular control sequence is only available if your
      terminal type is SNI-97801, or maybe it behaves slightly
      differently if your terminal type is SCOANSI.

      In K95, some behavior isn't assigned to specific terminal types,
      but specific *groups* of terminal types. A lot of terminal types
      behave *like* a VT100 (such as the linux console terminal). So
      rather than checking for 20 different terminal types everywhere
      VT100-like behavior is needed, it just checks if the current
      terminal type "ISVT100" - this means it actually *is* a VT100, or
      it's *compatible* with a VT100.

      The (badge) groups let that behavior be replicated here.
      Putting the "isvt100" group on a section applies all the badges in
      the "isvt100" group to that section. If the meaning of "ISVT100"
      in K95 changes someday to include an extra terminal type, all we
      need to do here is add the badge for that extra terminal type to
      the "isvt100" group and the badge for that extra terminal type
      will appear everywhere it needs to.

      The addition of the new Kermit 95 terminal type, and the need to
      have some reliable way to add it to all the places it needs to be
      in the ctlseqs.html document was the motivating factor in
      converting source of the document from HTML to XML.

    <refsrc> and <ref> Elements
      Where possible, references to terminal (or terminal emulator)
      documentation describing a given control sequence is described.

      The <ref> element applies to a section and produces a link to
      documentation relevant to that section. It has only a single
      attribute, src, which specifies a document key and value separated by a
      colon.

      The <refsrc> element describes a particular document that discusses
      control sequences, such as the VT520 programmers manual. The attributes
      are:
        - uri: where to find the document online. Prefer a source that is not
               likely to go offline for the forseeable future
        - name: This is used for hyperlinks to the document
        - key: This is used by <ref> elements to refer to the document
        - badge: Associate this document with a particular terminal
        - sort-order: Where links to this document appear relative to other
                documents
        - uri-type: What sort of link it is. Options are:
            - prefix: The value supplied by the <ref> element is concatenated
                    with the URI. For example, the <ref> element might specify
                    a filename.
            - pdf-page: The URI is to a PDF document, and individual pages can
                    be accessed by concatenating "#page=" followed by the value
                    supplied by the <ref> element which is assumed to be a page
                    number.
            - anchor: The URI is to a specific HTML document, and the value
                    supplied by the <ref> element is an anchor within that
                    document. The URI is joined to the <ref> elements value with
                    the # character.
        - pdf-page-offset: For the 'pdf-page' uri-type, this indicates the
                offset into the document that the page number refers to. That
                enables the page number shown to the user link links to match
                up with the page numbers as they appear in PDF document.

    <termsupp> Elements
       The termsupp elements indicate which other terminals are known or
       believed to implement a given control sequence or parameter. Any badges
       on a section, <ref> elements directly within that section which refer
       to a <refsrc> that specifies a badge also contribute this information.

       The original intention was the 'first' attribute would indicate which
       terminal originally introduced that control sequence, while the 'series'
       would indicate the family of terminals (eg, ANSI, DEC VT, etc) that
       control sequence belongs to. At the moment this information is, in many
       cases, not entirely accurate due in part to the time it would require to
       determine the first shipping terminal with a given escape sequence. So
       often 'first' is not really the first terminal, especially in cases where
       the control sequence was introduced by some terminal emulator rather than
       hardware terminal.

       As for what this information is actually used for? Right now it is only
       used for the term-ctlseqs comparison table, whose purpose is to help
       identify gaps in Kermit 95s compatibility with important terminals and
       terminal emulators. The goal is not to identify every terminal out there
       that ever implemented a given control sequence, just the ones that Kermit
       95 may someday want to emulate (eg, the VT520) or be compatible with (eg,
       xterm).

       Including Terminal Emulators does require a certain amount of ongoing
       maintenance work to keep the information up-to-date, so there needs to
       be a good reason to include one here.
       -> PuTTY
                 Because: It was probably the most popular terminal on Windows
                          for the last 20 years.
            Last Updated: 27 April 2025
                   As of: commit 01043ce4fc90cee578a00872a64fd69e4bb7203a
              Change Log: https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html
                          (updated on release only)
                          https://git.tartarus.org/?p=simon/putty.git;a=log
                          (Changes to this file may indicate support for new
                           control sequences)
       -> Tera Term
                 Because: It is the only free terminal with a similar feature
                          set to Kermit 95.
            Last Updated: 16 September 2025
                   As of: v5.5.0
              Change Log: https://teratermproject.github.io/manual/5/en/about/history.html
       -> Xterm
                 Because: It is the de-facto standard extended-VT terminal
            Last Updated: 8 September 2025
                   As of: Patch #402
              Change Log: https://invisible-island.net/xterm/xterm.log.html
       -> Windows Terminal
                 Because: It is the standard terminal on recent Windows releases
            Last Updated: 10 October 2025
                   As of: commit 5f311506dcaa93c24214819e02fa027151c47fe1
              Change Log: https://github.com/microsoft/terminal/commits/main/src/terminal/parser/OutputStateMachineEngine.cpp
                          (changes to this source file may indicate new
                           control sequences)
       -> CDE dtterm
          Capabilities should be current as of CDE 2.1.30 - dtterm doesn't
          appear to have received any new features since it was open-sourced
          back in 2012.
                 Because: It was the standard terminal on many proprietary unix
                          variants alongside xterm for many years, and it isn't
                          a moving target anymore which makes it a possible
                          candidate for future emulation.
            Last Updated: 27 August 2025
                   As of: commit 16fbb15ecc8cedfad6ce03e1891eed6fe28cedb0 (31 May 2018)
              Change Log: https://sourceforge.net/p/cdesktopenv/code/ci/9f0f015c4daf7d3eacb21c19b4f3912cac56e68e/log/?path=/cde/lib/DtTerm/Term/TermParseTable.c
                          (changes to this source file may indicate new
                           control sequences)
    -->

    <!-- TODO  - Merge the three mode sections into one
               - Replace the <ctlseq> element with:
                 - An <escseq> element for those that don't start with CSI
                 - A <param> element for describing parameters
                 - A new more structured <ctlseq> element which would have no
                    body and the following attributes:
                        - leading-character (one of <=>?  or nothing)
                        - parameter list type (fixed/variable)
                        - parameter kind - numeric, selective (if the two can be
                            mixed then this might have to become a parameter list)
                        - Intermediate characters
                        - final character
               - Add reference links for everything in the designate character
                 set tables
               - Add reference links to and any new escape sequences found in:
                   - The VT320 manual: EK-VT320-RM manual (if/when it turns up online)
                   - VT240, VT340 manuals
                   - The Sun console (man wscons)
                   - The SCO console (?)
                        Documented here: http://osr600doc.xinuos.com/en/man/html.HW/screen.HW.html
                        Terminal support tags have been added, references have not
                        as that document lacks anchors
                   - Non-control-sequences in ECMA-48
                   - Anything interesting here: https://bjh21.me.uk/all-escapes/all-escapes.xhtml
               - Consider moving VT52/H19 content into its own section
                   - Pro: - makes it easier to read
                          - xterms documentation does this
                   - Con: VT52 emulation has access to a lot of/most of the ANSI
                          escape sequences. Mixing it in with the ANSI emulation
                          makes this clear.
               - Add documentation and references for:
                   - Volker Craig (ckovc.c, 232 lines)
                   - ADM-3A (ckoadm.c, 292 lines)
                   - Hazeltine 1500 (ckohzl.c, 475 lines)
                   - AVATAR (ckoava.c, 542 lines)
                   - QNX (ckoqnx.c, 730 lines)
                   - Data General (ckodg.c, 1784 lines)
                   - Televideo (ckotvi.c, 2074 lines)
                   - IBM 31x1 (ckoi31.c, 2231 lines)
                   - HP (ckohp.c, 2997 lines)
                   - Wyse (ckowys.c, 5124 lines)
                 With the exception of AVATAR/0+, the code for all of these
                 is called from cwrite() followed by a return. If the terminal
                 has no emulation profiles (no ability to pretend to be, for
                 example, a VT100) then it should probably be covered in a
                 separate document. Perhaps it should be covered in a separate
                 document even if it *can* switch!
               - Add references to the designate character set tables
               - Check if the SCO "ESC xx" raw character thing (SCODPCC in the
                 VT520 manual) is implemented. If it is, then document it here.
                 SGR 10 & 11 seem to be related to this, possibly SGR 12 too
                 though thats only available to linux right now. I see code
                 which might be this feature, but it needs further inspection
                 and testing.
               - Update term references/termsupp elements for everything in this
                 spreadsheet
                 https://invisible-island.net/xterm/ctlseqs/dec_term_function_checklist.pdf
               - It would be neat if terminfo/termcap capability names/codes could
                 be stored against control sequences where they exist. This might
                 allow for interesting things like comparing K95 terminal
                 descriptions (as described by this document) with terminfo/termcap
                 descriptions, or generating a starting point for terminfo/termcap
                 descriptions from this document.
               - This document should, ideally, move away from just being a
                 collection of control sequences that K95 implements (or
                 doesn't) towards more of a proper reference manual for K95s
                 terminal emulator. Ideally readers wouldn't have to follow
                 links to, eg, the VT520 manual to find out what a control
                 sequence does.

    -->

    <!-- Page numbers for std 070
>> page 388, 389 references can be replaced <<

DECRPDE		343     Not in this document currently
C1 Control 	385		IND, NEL, HTS, RI, SS2, SS3, DCS, SOS, DECID, CSI, ST, OSC, PM, APC
SUB			387
DEC Priv	388		DECCKM, DECCOLM, DECSCLM, DECSCNM, DECOM, DECAWM, DECARM, DECPFF, DECPEX, DECCEM, DECTEK, DECNRCM, DECVCCM, DECPCCM, DECKBUM, DECLRMM, DECXRLM
DECRPM		450
DECRPSS		452
DECRQOSR	453
DECPSR		454
DECCIR		455
DECTSR		462
-->



    <!-- References to similar documentation elsewhere. This helps to identify
         other terminals (or terminal emulators) that support a given feature,
         as well as provide additional information about that feature.

         Reference sources require the following attributes:
            name - this is what's displayed in the generated HTML document
            key - more on this later
            uri - a base URI for the reference
            uri-type - how the base URI is used to create links
            sort-order - order in which references should be displayed when there
                         is more than one

        References are added to a section using the <ref> element, which takes
        a single "src" attribute. The attribute is a combination of key and
        a value separated by a colon. For example:
            <ref src="wy370:20"/>
        The key must match a refsrc element below, and the meaning of the value
        depends on the uri-type of the refsrc:
            anchor: the value is combined with the refsrc uri with the '#' character
            prefix: the value is combined with the refsrc uri with no joining character
            pdf-page: the value is combined with the refsrc uri with the string '#page='
                separating the two. The value is also shown alongside the name in
                the generated document in brackets with 'p' in front of it.
                For example:
                uri: foo.pdf
                uri-type: pdf-page
                name: document
                key: x
                reference: x:123
                resulting URI: foo.pdf#page=123
                resulting link: document (p123)
           pdf-page-offset: This can be used to show the numbered page in the
                document. In the above example, if pdf-page-offset is 23 then
                the display would be "document (p100/123)"
    -->
    <references>
        <!-- Xterm reference links all valid as of March 2025. No idea if they'll
             be stable long-term. Should probably write a script to check them.
             Might have to change this to a wayback link eventually. If that
              has to happen, the following wayback URI should work:
              https://web.archive.org/web/20250305175941/https://invisible-island.net/xterm/ctlseqs/ctlseqs.html-->
        <!-- All other reference links should also be valid as of March 2025 -->
        <refsrc name="ecma-48"
                key="e48"
                uri="https://ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf"
                uri-type="pdf-page"
                pdf-page-offset="14"
                sort-order="0"/>
        <refsrc name="ecma-43"
                key="e43"
                uri="https://ecma-international.org/wp-content/uploads/ECMA-43_3rd_edition_december_1991.pdf"
                uri-type="pdf-page"
                sort-order="10"/>
        <refsrc name="ecma-35"
                key="e35"
                uri="https://ecma-international.org/wp-content/uploads/ECMA-35_6th_edition_december_1994.pdf"
                uri-type="pdf-page"
                sort-order="20"/>
        <refsrc name="dec-std-070"
                key="070"
                uri="https://bitsavers.org/pdf/dec/standards/EL-SM070-00_DEC_STD_070_Video_Systems_Reference_Manual_Dec91.pdf"
                uri-type="pdf-page"
                sort-order="30"/>
        <refsrc name="dec-std-070"
                key="070h"
                uri="https://j4james.github.io/vtdocs/EL-00070-05.html"
                uri-type="anchor"
                sort-order="order=40"/>
        <refsrc name="vt52x"
                key="vt52x"
                uri="https://vt100.net/dec/ek-vt520-rm.pdf"
                uri-type="pdf-page"
                sort-order="41"
                badge="vt520"/>
        <refsrc name="vt510"
                key="vt510"
                uri="https://vt100.net/docs/vt510-rm/"
                uri-type="prefix"
                sort-order="50"
                badge="vt510"/>
        <refsrc name="vt420"
                key="vt420"
                uri="https://vt100.net/mirror/mds-199909/cd3/term/vt420rm2.pdf"
                uri-type="pdf-page"
                pdf-page-offset="22"
                sort-order="60"
                badge="vt420"/>
        <!-- Volume 1: Text Programming (EK-VT3XX-TP) -->
        <refsrc name="vt340"
                key="vt340"
                uri="http://www.bitsavers.org/pdf/dec/terminal/vt340/EK-VT3XX-TP-001_VT330_VT340_Text_Programming_Mar87.pdf"
                uri-type="pdf-page"
                pdf-page-offset="14"
                sort-order="70"/>
        <!-- Volume 2: Graphics Programming (EK-VT3XX-GP) -->
        <refsrc name="vt340"
                key="vt340g"
                uri="https://bitsavers.org/pdf/dec/terminal/vt340/EK-VT3XX-GP-001_VT330_VT340_Graphics_Programming_Mar87.pdf"
                uri-type="pdf-page"
                pdf-page-offset="16"
                sort-order="71"/>
        <!--TODO: Need to find a copy of EK-VT320-RM -->
        <refsrc name="vt220"
                key="vt220"
                uri="https://vt100.net/docs/vt220-rm/chapter4.html"