<?xml version="1.0" encoding="utf-8" ?>

<!--
    (C) Copyright David Goodwin, 2025.
    Permission is granted to copy, distribute and/or modify this document under
    the terms of the GNU Free Documentation License, Version 1.3 or any later
    version published by the Free Software Foundation; with no Invariant
    Sections, no Front-Cover Texts, and no Back-Cover Texts.
-->

<!--
This DTD is just here to help editors catch mistakes; the tool for converting
this document to HTML isn't quite as strict, and the DTD is not comprehensive.
-->
<!DOCTYPE document [
        <!ENTITY mdash "-">
        <!-- TODO - that really should be a proper mdash, but something
             (Regina REXX?) is converting everything to ASCII causing it to be
              mangled-->

        <!ATTLIST document title CDATA #REQUIRED>

        <!ELEMENT index EMPTY>

        <!ELEMENT badge-def EMPTY>
        <!ATTLIST badge-def name ID #REQUIRED>
        <!ATTLIST badge-def colour CDATA #IMPLIED>
        <!ATTLIST badge-def comment CDATA #IMPLIED>
        <!ATTLIST badge-def fg-color CDATA #IMPLIED>
        <!ATTLIST badge-def sort-order CDATA #IMPLIED>
        <!ELEMENT badges (badge-def)*>

        <!ELEMENT badge EMPTY>
        <!ATTLIST badge name IDREF #IMPLIED>
        <!ATTLIST badge group IDREF #IMPLIED>

        <!ELEMENT badgegroup-ref EMPTY>
        <!ATTLIST badgegroup-ref name IDREF #REQUIRED>

        <!ELEMENT badgegroup (badge|badgegroup-ref)*>
        <!ATTLIST badgegroup name ID #REQUIRED>
        <!ELEMENT badgegroups (badgegroup)*>


        <!ELEMENT k95info EMPTY>
        <!ATTLIST k95info val (herald|version-number|release|release-actual|version-full|version-date|version-date-short|version-date-iso|version-major|version-minor|version-rev|processed-date|processed-time) #REQUIRED>

        <!ELEMENT br EMPTY>

        <!ELEMENT em (#PCDATA)>
        <!ELEMENT tt (#PCDATA|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ELEMENT pre (#PCDATA|b)*>
        <!ELEMENT b (#PCDATA)>
        <!ELEMENT u (#PCDATA)>

        <!ELEMENT li (#PCDATA|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>

        <!ELEMENT ul (li)*>

        <!ELEMENT ol (li)*>

        <!ELEMENT dt (#PCDATA)>
        <!ATTLIST dt not-implemented (true|false) #IMPLIED>
        <!ELEMENT dd (#PCDATA|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>


        <!ELEMENT dl (dt,dd)*>

        <!ELEMENT a (#PCDATA|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ATTLIST a href CDATA #REQUIRED>

        <!ELEMENT param-single EMPTY>
        <!ATTLIST param-single symbol CDATA #IMPLIED>
        <!ATTLIST param-single value CDATA #IMPLIED>
        <!ATTLIST param-single description CDATA #IMPLIED>

        <!ELEMENT param-char EMPTY>
        <!ATTLIST param-char symbol CDATA #IMPLIED>
        <!ATTLIST param-char value CDATA #IMPLIED>
        <!ATTLIST param-char description CDATA #IMPLIED>

        <!ELEMENT param-multi EMPTY>
        <!ATTLIST param-multi symbol CDATA #IMPLIED>
        <!ATTLIST param-multi value CDATA #IMPLIED>
        <!ATTLIST param-multi description CDATA #IMPLIED>

        <!ELEMENT param-text EMPTY>
        <!ATTLIST param-text symbol CDATA #IMPLIED>
        <!ATTLIST param-text value CDATA #IMPLIED>
        <!ATTLIST param-text description CDATA #IMPLIED>

        <!ELEMENT p (#PCDATA|br|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>
        <!ATTLIST p role (code-reference|note|warning) #IMPLIED>
        <!ATTLIST p badges IDREFS #IMPLIED>
        <!ATTLIST p groups IDREFS #IMPLIED>
        <!ATTLIST p exclude-badges IDREFS #IMPLIED>

        <!ELEMENT th (#PCDATA|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info)*>

        <!ELEMENT td (#PCDATA|a|em|badge|tt|b|u|param-char|param-single|param-multi|param-text|k95info|br|table)*>
        <!ATTLIST td not-implemented (true|false) "false">
        <!ATTLIST td style CDATA #IMPLIED>
        <!ATTLIST td colspan CDATA #IMPLIED>

        <!ELEMENT tr (th|td)*>
        <!ATTLIST tr not-implemented (true|false) "false">

        <!ELEMENT table (tr)*>

        <!ELEMENT ctlseq (#PCDATA|param-char|param-single|param-multi|param-text)*>

        <!ELEMENT ref EMPTY>
        <!ATTLIST ref src CDATA #REQUIRED>
        <!ATTLIST ref comment CDATA #IMPLIED>

        <!ELEMENT termsupp EMPTY>
        <!ATTLIST termsupp series (vt|wyse|xt|k95|sco|rxvt|ansi|tt|linux|putty) #REQUIRED>
        <!ATTLIST termsupp first (vt50|vt50h|vt52|vt100|vt102|vt132|vt220|vt420|vt510|vt520|vt525|msk|k95|xterm|tt|wy370|ansi|sco|vt382|linux|putty) #REQUIRED>
        <!ATTLIST termsupp additional CDATA #IMPLIED>
        <!ATTLIST termsupp excluded CDATA #IMPLIED>

        <!ELEMENT section (ctlseq|ref|termsupp|p|ul|ol|dl|section|pre|table)*>
        <!ATTLIST section id ID #IMPLIED>
        <!ATTLIST section title CDATA #IMPLIED>
        <!ATTLIST section ctlseq CDATA #IMPLIED>
        <!ATTLIST section toc (true|false) "false">
        <!ATTLIST section groups IDREFS #IMPLIED>
        <!ATTLIST section badges IDREFS #IMPLIED>
        <!ATTLIST section exclude-badges IDREFS #IMPLIED>
        <!ATTLIST section exclude-groups IDREFS #IMPLIED>
        <!ATTLIST section hide-badges IDREFS #IMPLIED>
        <!ATTLIST section hide-groups IDREFS #IMPLIED>
        <!ATTLIST section style (box|group|none) "none">
        <!ATTLIST section not-implemented (true|false) "false">
        <!ATTLIST section todo (true|false) "false">
        <!ATTLIST section role (text|ctlseq|ctlchar|parameter|group) #REQUIRED>
        <!ATTLIST section formats CDATA #IMPLIED>
        <!ATTLIST section mnemonic CDATA #IMPLIED>

        <!ELEMENT refsrc EMPTY>
        <!ATTLIST refsrc key CDATA #REQUIRED>
        <!ATTLIST refsrc uri CDATA #IMPLIED>
        <!ATTLIST refsrc name CDATA #REQUIRED>
        <!ATTLIST refsrc uri-type (anchor|prefix|direct|pdf-page) #REQUIRED>
        <!ATTLIST refsrc sort-order CDATA #REQUIRED>
        <!ATTLIST refsrc pdf-page-offset CDATA #IMPLIED>
        <!ATTLIST refsrc badge IDREF #IMPLIED>

        <!ELEMENT references (refsrc)*>

        <!ELEMENT style (#PCDATA)>
        <!ELEMENT script (#PCDATA)>
        <!ELEMENT html (style?|script?)>
        <!ATTLIST html filename CDATA #REQUIRED>
        <!ATTLIST html type (document|outline|ctlseq-table|term-ctlseqs|todo) #REQUIRED>
        <!ATTLIST html title CDATA #IMPLIED>
        <!ATTLIST html todo-terminals CDATA #IMPLIED>  <!-- for "todo" type only -->
        <!ATTLIST html todo-ids CDATA #IMPLIED>  <!-- for "todo" type only -->
        <!ATTLIST html todo-mnemonics CDATA #IMPLIED>  <!-- for "todo" type only -->

        <!ELEMENT outputs (html)*>

        <!ELEMENT document (references | badges | badgegroups | outputs | section | index)*>
        ]>
<document title="Kermit 95 Default Keymaps">

    <!--
    ////////////////////////////// README //////////////////////////////
    This is the source document used to generate keyb.html which describes what
    Kermit 95s various default keymaps send
    -->

    <badges>
        <!-- These are all the terminal types supported by K95.
             If a color is not set, the badge will not be visible -->
        <badge-def sort-order="1"  name="aaa" colour="#9E9E9E" comment="Ann Arbor Ambassador"/>
        <badge-def sort-order="2"  name="adm3a" colour="dimgray" comment="LSI ADM 3A"/>
        <badge-def sort-order="3"  name="adm5" colour="dimgray" comment="LSI ADM 5"/>
        <badge-def sort-order="4"  name="aixterm" colour="#FFD740" comment="IBM AIXterm"/>
        <badge-def sort-order="5"  name="ansi" colour="#FFAB00" comment="IBM ANSI.SYS (BBS)"/>
        <badge-def sort-order="6"  name="at386" colour="#FFE082" comment="Unixware AT386 (Unix mode)"/>
        <badge-def sort-order="7"  name="avatar" colour="#B0BEC5" comment="AVATAR/0+ (same as ansi)"/> <!-- TODO: Hide -->
        <badge-def sort-order="8"  name="ba80" colour="#F4511E" comment="Nixdorf BA80"/>
        <badge-def sort-order="9"  name="beos" colour="#FFD54F" fg-color="white" comment="BeOS Ansi"/>
        <badge-def sort-order="10" name="dg200" colour="#E64A19" comment="Data General 200"/>
        <badge-def sort-order="11" name="dg210" colour="#D84315" comment="Data General 210"/>
        <badge-def sort-order="12" name="dg217" colour="#BF360C" comment="Data General 217"/>
        <badge-def sort-order="13" name="h19" colour="#B3E5FC" comment="Heath-19"/>
        <badge-def sort-order="14" name="hft" colour="#FFCA28" comment="IBM High Function Terminal"/>
        <badge-def sort-order="15" name="hp2621" colour="#78909C" comment="Hewlett-Packard 2621A"/>
        <badge-def sort-order="16" name="hpterm" colour="#607D8B" comment="Hewlett-Packard Console"/>
        <badge-def sort-order="17" name="hzl1500" colour="#757575" comment="Hazeltine 1500"/>
        <badge-def sort-order="18" name="ibm31" colour="dimgray" comment="IBM 31xx"/>
        <badge-def sort-order="19" name="k95" colour="#00E676" comment="Kermit 95"/>
        <badge-def sort-order="20" name="linux" colour="#FFC107" comment="Linux Console"/>
        <badge-def sort-order="21" name="qansi" colour="#FFB300" comment="QNX Ansi emulation"/>
        <badge-def sort-order="22" name="qnx" colour="#FFA000" comment="QNX"/>
        <badge-def sort-order="23" name="s97801" colour="#FF5722" comment="Sinix 97801-5xx terminal"/>
        <badge-def sort-order="24" name="scoansi" colour="#FF8F00" comment="SCOANSI (Unix mode)"/>
        <badge-def sort-order="25" name="sun" colour="#FF6F00" comment="SUN Console"/>
        <badge-def sort-order="26" name="tek40" colour="dimgray" comment="Tektronix 401x"/>
        <badge-def sort-order="27" name="tvi910" colour="dimgray" comment="TVI 910+"/>
        <badge-def sort-order="28" name="tvi925" colour="dimgray" comment="TVI 925"/>
        <badge-def sort-order="29" name="tvi950" colour="dimgray" comment="TVI 950"/>
        <badge-def sort-order="30" name="vc4404" colour="dimgray" comment="Volker Craig VC4404/404"/>
        <badge-def sort-order="31" name="vip7809" colour="olivedrab" comment="Honeywell VIP7809"/>
        <badge-def sort-order="32" name="vt52" colour="#90CAF9" comment="DEC VT-52"/>
        <badge-def sort-order="33" name="vt100" colour="#64B5F6" comment="DEC VT-100"/>
        <badge-def sort-order="34" name="vt102" colour="#42A5F5" comment="DEC VT-102"/>
        <badge-def sort-order="34" name="vt132" colour="" comment="DEC VT-132"/> <!-- Not implemented -->
        <badge-def sort-order="35" name="vt220" colour="#2196F3" comment="DEC VT-220"/>
        <badge-def sort-order="36" name="vt220pc" colour="" comment="DEC VT-220 with PC keyboard"/> <!-- Hide -->
        <badge-def sort-order="37" name="vt320" colour="#1E88E5" comment="DEC VT-320"/>
        <badge-def sort-order="38" name="vt320pc" colour="" comment="DEC VT-320 with PC keyboard"/> <!-- Hide -->
        <!-- Not implemented yet -->
        <badge-def sort-order="39" name="vt420" colour="" comment="DEC VT-420"/> <!-- colour: #1976D2 -->
        <badge-def sort-order="39" name="vt420pc" colour="" comment="DEC VT-420 with PC keyboard"/>
        <badge-def sort-order="40" name="vt510" colour="" comment="DEC VT-510"/> <!-- Not implemented -->
        <badge-def sort-order="40" name="vt520" colour="" comment="DEC VT-520"/> <!-- colour: #1565C0 -->
        <badge-def sort-order="40" name="vt520pc" colour="" comment="DEC VT-520 with PC keyboard"/>
        <badge-def sort-order="41" name="vt525" colour="" comment="DEC VT-525"/> <!-- colour: #0D47A1 -->
        <badge-def sort-order="42" name="vtnt" colour="dimgray" comment="Microsoft NT Virtual Terminal"/>
        <badge-def sort-order="43" name="wy30" colour="#009688" comment="WYSE-30/30+"/>
        <badge-def sort-order="44" name="wy50" colour="#00897B" comment="WYSE-50/50+"/>
        <badge-def sort-order="45" name="wy60" colour="#00796B" comment="WYSE-60"/>
        <badge-def sort-order="46" name="wy160" colour="#00695C" comment="WYSE-160"/>
        <badge-def sort-order="47" name="wy370" colour="#004D40" comment="WYSE 370 ANSI Terminal"/>
        <badge-def sort-order="48" name="xterm" colour="#F44336" comment="Xterm"/>
        <badge-def sort-order="49" name="tt" colour="" comment="Tera Term"/> <!-- Not implemented -->
        <badge-def sort-order="50" name="putty" colour="" comment="PuTTY"/> <!-- Not implemented -->

    </badges>
    <!--
     Badge groups should be kept in sync with the matching macros in ckuusr.h
     -->
    <badgegroups>
        <badgegroup name="isansi">
            <badge name="scoansi"/>
            <badge name="at386"/>
            <badge name="ansi"/>
        </badgegroup>
        <badgegroup name="isunixcon">
            <badge name="scoansi"/>
            <badge name="at386"/>
            <badge name="linux"/>
            <badge name="sun"/>
        </badgegroup>
        <badgegroup name="isdg200">
            <badge name="dg200"/>
            <badge name="dg210"/>
            <badge name="dg217"/>
        </badgegroup>
        <badgegroup name="istvi">
            <badge name="tvi910"/>
            <badge name="tvi925"/>
            <badge name="tvi950"/>
        </badgegroup>
        <badgegroup name="isvt52">
            <badge name="vt52"/>
            <badge name="h19"/>
        </badgegroup>
        <badgegroup name="isvt320">
            <!-- When these are implemented enough
            <badge name="vt525"/>
            <badge name="vt520"/>
            <badge name="vt420"/>-->
            <badge name="vt320"/>
            <badge name="vt320pc"/>
            <badge name="wy370"/>
            <badge name="s97801"/>
            <badge name="aaa"/>
            <badge name="k95"/>
        </badgegroup>
        <badgegroup name="isvt525">
            <!-- When VT525 is implemented enough, this should contain
                 only <badge name="vt525"/> -->
            <badgegroup-ref name="isvt320"/>
        </badgegroup>
        <badgegroup name="isvt520">
            <!-- When VT520 is implemented enough, this should contain
                 only <badge name="vt520"/> -->
            <badgegroup-ref name="isvt320"/>
        </badgegroup>
        <badgegroup name="isvt420">
            <!-- When VT420 is implemented enough, this should contain
                 only <badge name="vt420"/> and <badge name="vt520"> -->
            <badgegroup-ref name="isvt320"/>
        </badgegroup>
        <badgegroup name="isvt220">
            <badge name="vt220"/>
            <badge name="vt220pc"/>
            <badge name="vt320"/>
            <badge name="vt320pc"/>
            <badge name="wy370"/>
            <badge name="s97801"/>
            <badge name="aaa"/>
            <badge name="beos"/>
            <badge name="qansi"/>
            <badge name="linux"/>
            <badge name="sun"/>
            <badgegroup-ref name="isvt320"/>
            <!-- Why no AIXTERM? -->
        </badgegroup>
        <badgegroup name="isvt102">
            <badge name="vip7809"/>
            <badge name="linux"/>
            <badge name="hft"/>
            <badge name="aixterm"/>
            <badge name="sun"/>
            <badge name="ba80"/>
            <badge name="vt102"/>
            <badgegroup-ref name="isvt220"/>
        </badgegroup>
        <badgegroup name="isvt100">
            <badge name="vt100"/>
            <badgegroup-ref name="isvt102"/>
        </badgegroup>
        <badgegroup name="iswyse">
            <badge name="wy30"/>
            <badge name="wy50"/>
            <badge name="wy60"/>
            <badge name="wy160"/>
        </badgegroup>
        <badgegroup name="iswy60">
            <badge name="wy60"/>
            <badge name="wy160"/>
        </badgegroup>
        <badgegroup name="ishp">
            <badge name="hpterm"/>
            <badge name="hp2621"/>
        </badgegroup>
        <badgegroup name="ishft">
            <badge name="hft"/>
            <badge name="aixterm"/>
        </badgegroup>
        <badgegroup name="isxterm">
            <badge name="xterm"/>
        </badgegroup>
    </badgegroups>

    <!--
     This XML document is used to generate *multiple* different documents. The
     `formats` attribute on sections controls how those sections appear in the
     various documents, which are defined below
     -->
    <outputs>
        <!--
          This is the "full" document detailing what all the keys in Kermit 95s
          default keymaps do
         -->
        <html type="document" filename="keyb.html">
            <style>
                h2 { border-bottom: solid 2px; }
                h3 { border-bottom: solid 1px; }
                h4 { margin-left: 2em; }
                h5 { margin-left: 2em; }
                p { margin-left: 2em; }
                table { margin-left: 2em; }
                dl { margin-left: 2em; }
                pre { margin-left: 5em; }
                table, th, td { border: 1px solid black; border-collapse: collapse; }
                tr:hover {
                background-color: #4C8BF5;
                color: #fff;
                }
                .param { font-style: italic; }
                span.sec_ctlseq {
                margin-right: 5em;
                font-family: monospace;
                }
                h3 > span.sec_references {
                float: right;
                font-size: smaller;
                padding-left: 0.5em;
                }
                h4 > span.sec_ctlseq {
                margin-right: 0em;
                }
                h4 > span.sec_references {
                padding-left: 2em;
                font-size: smaller;
                }
                h4 > span.el_badges {
                margin-left: 2em;
                }
                span.badge {
                border-radius: 5px;
                padding: 4px 8px;
                text-transform: uppercase;
                margin-right: 5px;
                }
                div.todo {
                color: black;
                border-style: solid;
                border-color: orangered;
                background-color: coral;
                padding: 1em;
                margin-left: 2em;
                }
                div.box {
                border-style: solid;
                border-width: 1px;
                background-color: lightgray;
                margin-bottom: 5px;
                margin-left: 2em;
                }
                div.box > div.badges {
                padding-top: 4px;
                float: right;
                }
                div.box > div.badges > span.badge {
                border-radius: 0px;
                text-transform: uppercase;
                margin-right: 0px;
                }
                div.box > div.title {
                overflow:hidden;
                padding: 4px;
                text-align: center;
                background-color: black;
                color: white;
                }
                div.box > div.content {
                clear: left;
                padding: 4px 8px;
                margin-top: 1em;
                }
                .not-implemented { color: lightgray; }
                div.sec_group {
                margin-top: 1.33em;
                margin-bottom: 1.33em;
                }
                div.sec_group h4 {
                margin-top: 0px;
                margin-bottom: 0px;
                }
            </style>
        </html>
    </outputs>

    <section role="text">
        <p>
            <b>Kermit 95 Release:</b> <k95info val="version-full"/><br/>
            <b>Build Date:</b> <k95info val="version-date"/>
        </p>
        <p>
            This document attempts to describe what the default keymaps do for
            the terminal types covered in the
            <a href="ctlseqs.html">Kermit 95 Control Sequences</a> manual.
            This includes the default keybindings for each terminal type, and
            information about any referenced keyverbs.
        </p>
        <p>
            Prior to Kermit 95 v3.0 beta.8 there was no documentation that
            covered what various keys and keyverbs sent, only what they were.
            This document was produced by reading through all the kverb
            handling code and recording the responses they sent based on the
            varous terminal types. The keymap tables were generated by a script
            from default.ksc.
        </p>
    </section>

    <index/>

    <section title="Default Key Map" role="text" toc="true" id="keymap">
        <p>
            Kermit 95 includes keymaps suitable for each of the terminals it
            emulates. These keymaps specify what each key on the keyboard does;
            many keys just send themselves (the 'a' key sends ascii character
            \{98}, 'a'), while others may send either special
            <a href="#kverbs">Keyboard Verbs</a> whose definition may vary based
            on the current terminal type, or literal text including control
            sequences.
        </p>

        <p>
            In key definitions, where you see notation such as <tt>\{98}</tt>,
            that means send character 98 (decimal), which in this case is 'a'.
            You'll see \{27} (ESC) appear when a key (or keyboard verb) sends
            an escape sequence, for example.
        </p>

        <p>
            In addition to the terminal-specific keymaps shown int he table
            below (which can be modified with <tt>SET TERMINAL KEY</tt>), there
            are the additional <a href="#kmode">Special Keyboard Modes</a> which
            act as an overlay to modify the underlying terminal-specific keymap
            or user key definitions.
        </p>
        <pre>
                   [Special Keyboard Modes]
             +-----------+----------+----------+
             |           |          |          |
           EMACS      HEBREW     RUSSIAN   WORDPERFECT
             |           |          |          |
             +-----------+-----+----+----------+
                               |
                      [SET KEY Definitions]
                               |
           [Terminal-Emulation-Specific Definitions]
    +--------+--------+--------+--------+--------+--------+
    |        |        |        |        |        |        |
  VT52     VT100    VT220     WYSE    DG200     TVI      etc...
    |        |        |        |        |        |        |
    +--------+--------+--------+--------+--------+--------+
        </pre>

        <p>For the full details, see the <em>Key Mapping</em> section of the
            users guide.
        </p>

        <!-- This table was generated from default.ksc by a script
             (keymaps2xml.py)! Probably best to do that again if it needs any
              changes, rather than modifying it directly -->
        <!-- TODO: it would be rather handy if this *didn't* need to live here
             in this file... -->
        <table>
            <tr>
                <th>Key</th>
                <th>Key Code</th>
                <th>heath19</th>
                <th>vt52</th>
                <th>vt100</th>
                <th>vt102</th>
                <th>vt220</th>
                <th>vt320</th>
                <th>vt320pc</th>
                <th>vt220pc</th>
                <th>wy370</th>
                <th>ansi-bbs</th>
                <th>vip7809</th>
                <th>sni-97801</th>
                <th>scoansi</th>
                <th>at386</th>
                <th>linux</th>
                <th>beterm</th>
                <th>qansi</th>
                <th>tty</th>
                <th>annarbor</th>
                <th>ibm3151</th>
                <th>ba80</th>
                <th>aixterm</th>
                <th>hft</th>
                <th>sun</th>
            </tr>
            <tr>
                <td>DLE</td>
                <td>\16</td>
                <td colspan="24"><a href="#kverb_Kignore">\Kignore</a></td>
            </tr>
            <tr>
                <td>DC1</td>
                <td>\17</td>
                <td colspan="24"><a href="#kverb_Kignore">\Kignore</a></td>
            </tr>
            <tr>
                <td>DC2</td>
                <td>\18</td>
                <td colspan="24"><a href="#kverb_Kignore">\Kignore</a></td>
            </tr>
            <tr>
                <td>Backspace</td>
                <td>\264</td>
                <td colspan="11">\{127}</td>
                <td colspan="5">\{8}</td>
                <td colspan="5">\{127}</td>
                <td colspan="3">\{8}</td>
            </tr>
            <tr>
                <td>Tab</td>
                <td>\265</td>
                <td style="not-mapped" colspan="11"/>
                <td><a href="#kverb_Ksni_tab">\Ksni_tab</a></td>
                <td style="not-mapped" colspan="3"/>
                <td>\{9}</td>
                <td style="not-mapped" colspan="8"/>
            </tr>
            <tr>
                <td>Clear</td>
                <td>\268</td>
                <td colspan="11"><a href="#kverb_Kkp5">\Kkp5</a></td>
                <td style="not-mapped"/>
                <td colspan="3"><a href="#kverb_Kansif54">\Kansif54</a></td>
                <td><tt>\{27}[G</tt></td>
                <td style="not-mapped" colspan="7"/>
                <td><tt>\{27}[218z</tt></td>
            </tr>
            <tr>
                <td>Enter</td>
                <td>\269</td>
                <td colspan="24">\{13}</td>
            </tr>
            <tr>
                <td>Pause</td>
                <td>\275</td>
                <td style="not-mapped" colspan="23"/>
                <td><tt>\{27}[208z</tt></td>
            </tr>
            <tr>
                <td>CapsLock</td>
                <td>\276</td>
                <td colspan="24"><a href="#kverb_Kignore">\Kignore</a></td>
            </tr>
            <tr>
                <td>PageUp</td>
                <td>\289</td>
                <td colspan="11"><a href="#kverb_Kkp9">\Kkp9</a></td>
                <td style="not-mapped"/>
                <td colspan="3"><a href="#kverb_Kansif51">\Kansif51</a></td>
                <td>\{11}</td>
                <td><tt>\{27}[V</tt></td>
                <td style="not-mapped" colspan="6"/>
                <td><tt>\{27}[216z</tt></td>
            </tr>
            <tr>
                <td>PageDown</td>
                <td>\290</td>
                <td colspan="11"><a href="#kverb_Kkp3">\Kkp3</a></td>
                <td><a href="#kverb_Kdnscn">\Kdnscn</a></td>
                <td colspan="3"><a href="#kverb_Kansif59">\Kansif59</a></td>
                <td>\{12}</td>
                <td><tt>\{27}[U</tt></td>
                <td colspan="6"><a href="#kverb_Kdnscn">\Kdnscn</a></td>
                <td><tt>\{27}[222z</tt></td>
            </tr>
            <tr>
                <td>End</td>
                <td>\291</td>
                <td colspan="11"><a href="#kverb_Kkp1">\Kkp1</a></td>
                <td><a href="#kverb_Kendscn">\Kendscn</a></td>
                <td colspan="3"><a href="#kverb_Kansif57">\Kansif57</a></td>
                <td>\{4}</td>
                <td colspan="7"><a href="#kverb_Kendscn">\Kendscn</a></td>
                <td><tt>\{27}[220z</tt></td>
            </tr>
            <tr>
                <td>Home</td>
                <td>\292</td>
                <td colspan="11"><a href="#kverb_Kkp7">\Kkp7</a></td>
                <td><a href="#kverb_Khomscn">\Khomscn</a></td>
                <td colspan="3"><a href="#kverb_Kansif49">\Kansif49</a></td>
                <td>\{1}</td>
                <td><tt>\{27}[H</tt></td>
                <td colspan="6"><a href="#kverb_Khomscn">\Khomscn</a></td>
                <td><tt>\{27}[214z</tt></td>
            </tr>
            <tr>
                <td>LeftArrow</td>
                <td>\293</td>
                <td colspan="11"><a href="#kverb_Kkp4">\Kkp4</a></td>
                <td><a href="#kverb_Klfarr">\Klfarr</a></td>
                <td colspan="3"><a href="#kverb_Kansif53">\Kansif53</a></td>
                <td>\{28}</td>
                <td colspan="8"><a href="#kverb_Klfarr">\Klfarr</a></td>
            </tr>
            <tr>
                <td>UpArrow</td>
                <td>\294</td>
                <td colspan="11"><a href="#kverb_Kkp8">\Kkp8</a></td>
                <td><a href="#kverb_Kuparr">\Kuparr</a></td>
                <td colspan="3"><a href="#kverb_Kansif50">\Kansif50</a></td>
                <td>\{30}</td>
                <td colspan="8"><a href="#kverb_Kuparr">\Kuparr</a></td>
            </tr>
            <tr>
                <td>RightArrow</td>
                <td>\295</td>
                <td colspan="11"><a href="#kverb_Kkp6">\Kkp6</a></td>
                <td><a href="#kverb_Krtarr">\Krtarr</a></td>
                <td colspan="3"><a href="#kverb_Kansif55">\Kansif55</a></td>
                <td>\{29}</td>
                <td colspan="8"><a href="#kverb_Krtarr">\Krtarr</a></td>
            </tr>
            <tr>
                <td>DownArrow</td>
                <td>\296</td>
                <td colspan="11"><a href="#kverb_Kkp2">\Kkp2</a></td>
                <td><a href="#kverb_Kdnarr">\Kdnarr</a></td>
                <td colspan="3"><a href="#kverb_Kansif58">\Kansif58</a></td>
                <td>\{31}</td>
                <td colspan="8"><a href="#kverb_Kdnarr">\Kdnarr</a></td>
            </tr>
            <tr>
                <td>Print</td>
                <td>\298</td>
                <td style="not-mapped" colspan="21"/>
                <td colspan="2"><tt>\{27}[209q</tt></td>
                <td><tt>\{27}[209z</tt></td>
            </tr>
            <tr>
                <td>Insert</td>
                <td>\301</td>
                <td colspan="11"><a href="#kverb_Kkp0">\Kkp0</a></td>